USE metro_cdmx;

INSERT INTO `stations` (`name`) VALUES
("lázaro cárdenas"), 
("ferrería"),  
("pantitlán"),  
("tacuga"),  
("martín carrera"),  
("santa anita"), 
("villa de aragón"), 
("tezozómoc"), 
("tecnológico"), 
("colegio militar"), 
("chapultepec"), 
("calle 11"), 
("constitución de 1917"), 
("copilco"), 
("talismán"), 
("terminal aérea"), 
("tepito"), 
("hospital 20 de nov."), 
("eugenia"), 
("lomas estrella"), 
("tlatelolco"), 
("atlalilco"), 
("blvd. puerto aéreo"), 
("chilpancingo"), 
("ciudad azteca"), 
("niños héroes"), 
("popotla"), 
("san joaquín"), 
("universidad"), 
("instituto del petróleo"), 
("escuadrón 201"), 
("iztacalco"), 
("juárez"), 
("chabacano"), 
("azcapotzalco"), 
("bosque de aragón"), 
("tlaltenco"), 
("jamaica"), 
("oceanía"), 
("iztapalapa"), 
("mixhuca"), 
("centro médico"), 
("balderas"), 
("salto del agua"), 
("insurgentes"), 
("guelatao"), 
("morelos"), 
("moctezuma"), 
("normal"), 
("zapata"), 
("zaragoza"), 
("la raza"), 
("constituyentes"), 
("múzquiz"), 
("romero rubio"), 
("san cosme"), 
("portales"), 
("puebla"), 
("santa marta"), 
("tasqueña"), 
("xola"), 
("canal del norte"), 
("buenavista"), 
("balbuena"), 
("ermita"), 
("aragón"), 
("deportivo 18 de marzo"), 
("auditorio"), 
("culhuacán"), 
("el rosario"), 
("guerrero"), 
("hospital general"), 
("fray servando"), 
("patriotismo"), 
("observatorio"), 
("la paz"), 
("valle gómez"), 
("tezonco"), 
("candelaria"), 
("aquiles serdán"), 
("la viga"), 
("olímpica"), 
("mexicaltzingo"), 
("politécnico"), 
("periférico ote"), 
("san lázaro"), 
("san antonio"), 
("zapotitlán"), 
("tláhuac"), 
("hidalgo"), 
("etiopía / plaza de la transpatencia"), 
("deportivo oceanía"), 
("impulsora"), 
("consulado"), 
("camarones"), 
("allende"), 
("san juan de letrán"), 
("viaducto"), 
("vallejo"), 
("doctores"), 
("los reyes"), 
("bellas artes"), 
("autobuses del norte"), 
("acatitla"), 
("revolución"), 
("polanco"), 
("san andrés tomatlán"),
 ("garibaldi"), 
 ("eduardo molina"), 
 ("coyuya"), 
 ("coyoacán"), 
 ("norte 45"), 
 ("lindavista"), 
 ("tacubaya"), 
 ("mixcoac"), 
 ("hangares"), 
 ("nopalera"), 
 ("uam-i"), 
 ("velódromo"), 
 ("cuauhtémoc"), 
 ("apatlaco"), 
 ("aculco"), 
 ("agrícola oriental"), 
 ("eje central"), 
 ("pino suárez"), 
 ("río de los remedios"), 
 ("potrero"), 
 ("sevilla"), 
 ("general anaya"), 
 ("indios verdes"), 
 ("la villa - basílica"), 
 ("parque de los venados"), 
 ("juanacatlán"), 
 ("nativitas"), 
 ("misterios"), 
 ("barranca del muerto"), 
 ("miguel ángel de quevedo"), 
 ("lagunilla"), 
 ("olivos"), 
 ("tepalcates"), 
 ("zócalo"), 
 ("gómez farías"), 
 ("san pedro de los pinos"), 
 ("refinería"), 
 ("villa de cortés"), 
 ("r. flores magón"), 
 ("insurgentes sur"), 
 ("viveros"), 
 ("cerro de la estrella"), 
 ("bondojito"), 
 ("canal de san juan"), 
 ("san antonio abad"), 
 ("obrera"), 
 ("plaza aragón"), 
 ("panteones"), 
 ("peñón viejo"), 
 ("división del norte"), 
 ("cuitláhuac"), 
 ("ciudad deportiva"), 
 ("cuatro caminos"), 
 ("isabel la católica"),
  ("nezahualcóyotl"), 
  ("merced"), 
  -- a partir de aquí serán retos para eliminar registros 
  ("merced"), 
  ("lázaro de guerrero"), 
  ("benito cárdenas");